spring:
  mail:
    protocol: smtp
    properties.mail:
      smtp:
        auth: true
      debug: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
        security: TRACE
    com.giffing.bucket4j.spring.boot.starter: DEBUG
    io.github.bucket4j: DEBUG

debug: true