spring:
  mail:
    protocol: smtp
    properties.mail:
      smtp:
        auth: true
      debug: true

# Local dev JWT keys (these files are gitignored)
jwt:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
        security: TRACE
    com.giffing.bucket4j.spring.boot.starter: DEBUG
    io.github.bucket4j: DEBUG

debug: true