#!/usr/bin/env python3
"""Check every receipt in ground-truth.json against its own printed totals,
then regenerate the readable table.

Run this after editing ground-truth.json. It is the only thing you need to run:
it validates the labels and rewrites ground-truth.md from them.

Validation is what makes the labels auditable rather than trusted. A receipt
prints its own total; if the transcribed items minus the discounts do not equal
it, the transcription is wrong and no one has to take anyone's word for it.
Receipts printing both a lev and a euro total give a second, independent check.
"""
from __future__ import annotations
import json, sys
from pathlib import Path

FIX = Path(__file__).resolve().parent.parent.parent / 'receipt-fixtures'
SRC = FIX / 'ground-truth.json'


def check(r: dict, rate: float) -> dict:
    items = r.get('items') or []
    gross = round(sum(i.get('price', 0) for i in items), 2)
    line = round(sum(i.get('discount', 0) or 0 for i in items), 2)
    basket = round(sum(r.get('basket_discounts') or []), 2)
    net = round(gross - line - basket, 2)
    out = {'gross': gross, 'line_discounts': line, 'basket_discounts': basket,
           'net': net, 'problems': []}

    total = r.get('total')
    out['reconciles'] = None
    if total is not None:
        out['reconciles'] = abs(net - total) < 0.05
        if not out['reconciles']:
            out['problems'].append(f"items net to {net:.2f} but the receipt says {total:.2f} "
                                   f"({net - total:+.2f})")

    # a printed pair of totals validates the reading a second, independent way
    pair = None
    if total and r.get('total_eur') and r.get('currency') == 'BGN':
        pair = abs(total / rate - r['total_eur']) < 0.03
    elif total and r.get('total_bgn') and r.get('currency') == 'EUR':
        pair = abs(total * rate - r['total_bgn']) < 0.03
    out['currency_pair'] = pair
    if pair is False:
        out['problems'].append('the printed lev and euro totals do not agree at 1.95583')

    for i in items:
        if i.get('quantity') and i.get('unit_price'):
            if abs(i['quantity'] * i['unit_price'] - i['price']) > 0.03:
                out['problems'].append(
                    f"{i['name']}: {i['quantity']} x {i['unit_price']} != {i['price']}")
    if not items and total:
        out['problems'].append('no items transcribed')
    return out


def main() -> int:
    if not SRC.exists():
        sys.exit(f'not found: {SRC}')
    try:
        doc = json.loads(SRC.read_text())
    except json.JSONDecodeError as e:
        sys.exit(f'ground-truth.json is not valid JSON: line {e.lineno}, column {e.colno}: {e.msg}')

    rate = doc.get('_rate', 1.95583)
    rows = []
    for fx, r in sorted(doc['receipts'].items()):
        rows.append((fx, r, check(r, rate)))

    ok = [x for x in rows if x[2]['reconciles']]
    bad = [x for x in rows if not x[2]['reconciles']]
    print(f"{'fixture':34} {'total':>8} {'net':>8} {'items':>5}  status")
    print('-' * 88)
    for fx, r, c in rows:
        flag = 'ok' if c['reconciles'] else (c['problems'][0][:40] if c['problems'] else 'no total')
        print(f"{fx:34} {r.get('total') or 0:>8.2f} {c['net']:>8.2f} "
              f"{len(r.get('items') or []):>5}  {flag}")
    print('-' * 88)
    print(f"  {len(rows)} receipts · {len(ok)} verified · {len(bad)} need review")

    L = ['# Ground truth — audit table', '',
         '> Generated by `scripts/verify-ground-truth.py`. **Do not edit.**',
         '> The source is `ground-truth.json`; edit that and re-run the script.', '',
         f'**{len(rows)} receipts · {len(ok)} verified · {len(bad)} need review**', '',
         'Each receipt is checked against its own printed total: items minus discounts',
         'must equal it. Where both a lev and a euro total are printed, they are checked',
         f'against 1 EUR = {rate} BGN — an independent second confirmation.', '',
         '| fixture | store | cur | total | net | items | pair | ✓ |',
         '|---|---|---|---|---|---|---|---|']
    for fx, r, c in rows:
        pair = 'Y' if c['currency_pair'] else ('N' if c['currency_pair'] is False else '—')
        L.append(f"| {fx} | {r.get('store','?')} | {r.get('currency','?')} | "
                 f"{r.get('total') or 0:.2f} | {c['net']:.2f} | {len(r.get('items') or [])} | "
                 f"{pair} | {'Y' if c['reconciles'] else '**N**'} |")
    if bad:
        L += ['', f'## Need review ({len(bad)})', '']
        for fx, r, c in bad:
            L.append(f"**`{fx}`**")
            for p in c['problems']:
                L.append(f"  - {p}")
            if r.get('_note'):
                L.append(f"  - _{r['_note']}_")
            L.append('')
    (FIX / 'ground-truth.md').write_text('\n'.join(L) + '\n')
    print(f"  table rewritten: {FIX / 'ground-truth.md'}")
    return 0 if not bad else 1


if __name__ == '__main__':
    raise SystemExit(main())
